### ISSUE TITLE
Enable WEBP/PSD/TGA/TIFF/PCX/LZP support via IFDEFs

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#159] opened 2021-12-28 09:56 UTC
If IFDEF off, code won't be bloated (these formats are often not needed if a man only needs the bitmap render code).

**Comment by circular17** [comment] 2022-06-04 23:22
Kind of duplicate of big exe footprint

**Closed by circular17** 2022-06-04 23:22 UTC
